### PR TITLE
fix Append '\n' not work

### PR DESCRIPTION
**Pull request by joesdu**

### CODE REVIEW

**Comment by xciser77** [comment]
is this fixed? because when I add a command with the toggle Append \n off is still does a Enter/Return when selecting the command

**Comment by joesdu** [comment]
[Demo Video] (https://oss.altzyxy.com/others/Video_2023-11-22_172240.wmv)
The original plug-in will enter a carriage return in any case, causing the command to be executed immediately.

**Comment by joesdu** [comment]
You can copy my compiled plugin to the following directory for testing: 
```code
C:\Users\{Your Name}\AppData\Roaming\tabby\plugins\node_modules\tabby-quick-cmds
```
[dist.zip](https://github.com/minyoad/terminus-quick-cmds/files/13437338/dist.zip)

**Comment by joesdu** [comment]
不再使用tabby，tabby基于electron开发体验太差了

**Pull request closed without merging**
